### ISSUE TITLE
results.rss is undefined - Can't find posts

### ISSUE THREAD

**Issue by mMoovs** [christianv/jquery-lifestream#192]
I noticed today that this isn't showing anything anymore and in console I get error:
n.query.results.rss is undefined

I'm using this only to get facebook-posts so did Facebook change something at their end once again or what, any ideas?

**Comment by christianv** [comment]
@mMoovs indeed, seems like they removed their public RSS feed for facebook pages:
https://www.facebook.com/feeds/page.php?id=103257716379127&format=rss20

**Comment by christianv** [comment]
http://stackoverflow.com/questions/28202262/did-facebook-recently-disable-accessing-public-page-feeds-via-uri

**Comment by mMoovs** [comment]
Ok. And it looks like you can't get the feed with Graph API without Access Token. I really wouldn't want to ask all users for permission so they can just see the FB feed posts.

Have you possibly figured out some workaround for this? I got this script on a few pages showing just the facebook posts so it's really needed :)

**Comment by christianv** [comment]
Another post from a user:

> Hi - I've been testing jquery Lifestream for a project I'm working on, and it works GREAT !  I'm able to get twitter and Flickr to work just fine, but I cannot seem to get Facebook feeds to work.
>Has anything changed recently?
>When I tested this a couple of weeks ago, it seemed to work fine, but now I cannot get the Facebook feed to work.
>Thinking it might be my poor use of your excellent code, I went back to the demo page (http://christianv.github.io/jquery-lifestream/me/), and tried to get Facebook feeds to work there, but they don't.  I tried several different Facebook pages, in case it was the page I was working on, but I can't get anything to work. (I also tried several different browsers, but that doesn't seem to be the problem).
>Any insight would be most appreciated!

**Comment by christianv** [comment]
Seems like they re-enabled it. So closing for now

**Comment by mMoovs** [comment]
Yup, looks like the RSS feed was disabled by a mistake this time. But they're going to remove it later this year and then we got the same problem again so I think this is still an issue...
https://developers.facebook.com/bugs/1539780319626180/

Do you think you might be able to get it working through the Graph API somehow? Maybe with a hadrcoded dummy access token?

**Comment by suragprajapati** [comment]
Looks like they have deprecated the RSS feed and officially not working from Jun 23rd 2015. They are asking to call Graph API and get the access tokens. Any work around for this?

**Comment by christianv** [comment]
@suragprajapati we'll need a scraper for this if we don't want to add the extra keys.

**Comment by christianv** [comment]
Seems like this broke again follow up at #198
