### ISSUE TITLE
Facebook stream no longer working

### ISSUE THREAD

**Issue by sharpmachine** [christianv/jquery-lifestream#195]
Hi there,

the Lifestream for http://bjm.org used to work just find but now it's stopped working.  Nothing has changed on the code side of things so I'm a little lost here.  The facebook page id is 54557413386.

Even if I go to the create your own stream page for the Lifestream demo it still doesn't work.  But if I test it with a different facebook id number for a different Facebook page, it works. 

Any help would be appreciated.

**Comment by christianv** [comment]
@sharpmachine indeed, it looks like the facebook pages api still works for most accounts. Are you able to see the posts through any other way? RSS / API / ...

**Comment by tonytals** [comment]
@sharpmachine I looked at the font of your website and I not found the link to lifestream.js...

**Comment by sharpmachine** [comment]
@tonytals it's concatenated and minified within plugins-min.js.

@christianv I'm not sure if I can or not.  I don't know how to check that.

**Comment by christianv** [comment]
We'll probably need to write our own scraper as we do with twitter: http://twittery.herokuapp.com/denbuzze

**Comment by sharpmachine** [comment]
Hey @christianv.  I'm still having the issue with the feed not working.  Any help would be awesome!

**Comment by christianv** [comment]
@sharpmachine we would need a scraper to expose our own YouTube API. I currently don't have the bandwidth to write one. Have a look at https://github.com/christianv/twittery to see how we could get started.

**Comment by sharpmachine** [comment]
YouTube?  The feed I'm talking about is a Facebook feed.

**Comment by christianv** [comment]
@sharpmachine sorry, had the wrong ticket in mind, can you verify that this is the feed that you are looking for: http://www.facebook.com/feeds/page.php?format=rss20&id=54557413386

**Comment by sharpmachine** [comment]
No problem!

Yes that's the feed.

**Comment by christianv** [comment]
Since that feed is working, but the YQL version is not, we'll probably have to create our own proxy (or use an existing one that works with our feeds)

**Comment by sharpmachine** [comment]
Is there anything I need to do?

**Comment by christianv** [comment]
@sharpmachine if you're comfortable developing our own proxy (have a look at https://github.com/christianv/twittery) in NodeJS, go ahead. If not I'll try to find some time to work on this.

**Comment by sharpmachine** [comment]
I wish I was that skilled but I'm a UX designer trying to do a bit of front-end stuff.

**Comment by christianv** [comment]
@sharpmachine just landed a fix - https://christianv.github.io/jquery-lifestream/me/#facebook_page=54557413386 should now be working again.

If you're interested:
https://github.com/christianv/facebooky
https://facebooky.herokuapp.com/54557413386

**Comment by sharpmachine** [comment]
Beautiful!  Thanks @christianv !

**Comment by christianv** [comment]
Seems like this broke again up at #198
