### ISSUE TITLE
Facebook not working

### ISSUE THREAD

**Issue by romymk** [christianv/jquery-lifestream#200]
I have made the update to https, and Facebook feed is still not loading.  I have tried your lifestream building tool, and nothing displays for the Facebook Page.  Any suggestions on how to fix?  Thanks much.

**Comment by christianv** [comment]
@romymk what ID are you using? What is the link of the facebook page you're trying to show?

**Comment by romymk** [comment]
The page is facebook.com/airguyana. ID: 135847876455788

I have tested lifestream generate page with a of couple IDs, but none generated a feed.  The other social media feeds were generated.

**Comment by christianv** [comment]
@romymk you're right, looks like this is a duplicate of #198 and we still don't have a fix after facebook shut down their public access

**Comment by romymk** [comment]
@christianv I only notice #198 after I had posted, thus closing this thread.  I will keep checking #198 for any resolutions.  Thank you for this wonderful script. It's very useful.
